//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnListToColumn
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> OrderInList { get; set; }
        public int ColumnListToColumn_Column { get; set; }
        public int ColumnListToColumn_ColumnList { get; set; }
    
        public virtual ColumnList ColumnList { get; set; }
        public virtual Column Column { get; set; }
    }
}
