//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPoint
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<double> Value { get; set; }
        public int DataPoint_Row { get; set; }
        public int DataPoint_Column { get; set; }
        public int ExecutionResultSet_DataPoint { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Row Row { get; set; }
        public virtual ExecutionResultSet ExecutionResultSet { get; set; }
    }
}
