//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSnippet
    {
        public ReportSnippet()
        {
            this.ReportSnippetToReportDefinitions = new HashSet<ReportSnippetToReportDefinition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ReportSnippet_RowList { get; set; }
        public int ReportSnippet_ColumnList { get; set; }
    
        public virtual ColumnList ColumnList { get; set; }
        public virtual RowList RowList { get; set; }
        public virtual ICollection<ReportSnippetToReportDefinition> ReportSnippetToReportDefinitions { get; set; }
    }
}
