//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDefinition
    {
        public ReportDefinition()
        {
            this.ReportSnippetToReportDefinitions = new HashSet<ReportSnippetToReportDefinition>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ReportSnippetToReportDefinition> ReportSnippetToReportDefinitions { get; set; }
    }
}
