//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSnippetToReportDefinition
    {
        public int Id { get; set; }
        public int ReportSnippetToReportDefinitio_ReportDefinition { get; set; }
        public int ReportSnippetToReportDefinitio_ReportSnippet { get; set; }
    
        public virtual ReportDefinition ReportDefinition { get; set; }
        public virtual ReportSnippet ReportSnippet { get; set; }
    }
}
