//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESim.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingChoiceToSettingChoiceSet
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int SettingChoiceToSettingChoiceSe_SettingChoice { get; set; }
        public int SettingChoiceToSettingChoiceSe_SettingChoiceSet { get; set; }
    
        public virtual SettingChoice SettingChoice { get; set; }
        public virtual SettingChoiceSet SettingChoiceSet { get; set; }
    }
}
