using ACESim;
using System.Text.Json.Nodes;

namespace ArticleReplication;

public static class WelfareSupplement
{
    static readonly string[] Labels=["Meritorious plaintiff shortfall","Nonliable defendant burden","Liable defendant excess burden","Gross outcome error","Real litigation expenditures"];
    static string Tex(string s)=>MainTables.Escape(s);
    static string Risk(FinalArticleCase p)=>p.AlphaP==0&&p.AlphaD==0?"RN":p.AlphaP==p.AlphaD?$"RA ({p.AlphaP:G})":$"P {p.AlphaP:G}, D {p.AlphaD:G}";
    static string Specification(FinalArticleCase p)=>(p.IsExternalImport?"Baseline":p.Family+" / "+p.Variant)+$"; cost {p.CostMultiplier:G}";
    static string Number(double v)=>Math.Abs(v)<.0005?"0.000"+(v==0?"":@"$^{\dagger}$"):v.ToString("F3");
    static void Near(double a,double b){if(!double.IsFinite(a)||Math.Abs(a-b)>1e-10)throw new InvalidDataException("Welfare report identity failed.");}
    static List<string> Begin(string margin,string packages)=>[@"\documentclass[10pt]{article}",$"\\usepackage[paperwidth=11in,paperheight=8.5in,margin={margin}in,footskip=16pt]{{geometry}}",@"\usepackage[T1]{fontenc}\usepackage{lmodern}",@"\usepackage{booktabs,longtable,array,"+packages+"}",@"\setlength{\parindent}{0pt}\begin{document}"];
    public static void Generate(ResolvedArticlePlan plan,Dictionary<string,(JsonObject Audit,JsonObject Profile)> profiles,string collection,string run)
    {
        var cases=plan.Cases.Where(c=>profiles.ContainsKey(c.Id)).OrderBy(Specification,StringComparer.Ordinal).ThenBy(Risk,StringComparer.Ordinal).ThenBy(c=>c.FeeRule,StringComparer.Ordinal).ToArray();
        var pairs=plan.Welfare.Where(p=>profiles.ContainsKey(p.Source)&&profiles.ContainsKey(p.Target)).OrderBy(p=>p.Source,StringComparer.Ordinal).ToArray();
        var data=pairs.Select(p=>Files.Object(Path.Combine(run,"ReportResults/Welfare",p.Id,"decomposition.json"))).ToArray();
        double Level(string id,string measure)=>profiles[id].Audit["Welfare"]!["Headline"]![measure]!.GetValue<double>();
        for(int i=0;i<pairs.Length;i++)for(int j=0;j<Labels.Length;j++)
        {
            if(data[i]["Passed"]?.GetValue<bool>()!=true)throw new InvalidDataException("Failed welfare calculation.");var c=data[i]["Components"]![Labels[j]]!;
            double aa=c["AmericanWithAmericanProfile"]!.GetValue<double>(),ca=c["CompleteWithAmericanProfile"]!.GetValue<double>(),ac=c["AmericanWithCompleteProfile"]!.GetValue<double>(),cc=c["CompleteWithCompleteProfile"]!.GetValue<double>();
            if(aa!=Level(pairs[i].Source,WelfareFigure.Measures[j])||cc!=Level(pairs[i].Target,WelfareFigure.Measures[j]))throw new InvalidDataException("Welfare endpoint changed.");
            Near((ca-aa+cc-ac)/2,c["MechanicalRuleEffect"]!.GetValue<double>());Near((ac-aa+cc-ca)/2,c["BehavioralEffect"]!.GetValue<double>());Near(cc-aa,c["TotalDifference"]!.GetValue<double>());
        }
        string root=Path.Combine(collection,"Supplemental materials/Generated pairwise comparisons");Directory.CreateDirectory(Path.Combine(root,"Sources"));
        Files.Save(Path.Combine(root,"Sources/welfare.generated-data.json"),new{Cases=cases.Select(c=>new{Parameters=c,Welfare=profiles[c.Id].Audit["Welfare"]}),Comparisons=pairs.Select((p,i)=>new{Code=$"C{i+1:D2}",Pair=p,Components=data[i]["Components"]}),ExpectedPrimary=plan.Cases.Length,ExpectedComparisons=plan.Welfare.Length,Pending=plan.Cases.Where(c=>!profiles.ContainsKey(c.Id)),TruthMapping="identity",FreshEndpointChecks=true});
        var lines=Begin(".45","pgfplots");lines.Insert(4,@"\pgfplotsset{compat=1.18}");
        lines.AddRange([@"{\LARGE\bfseries Baseline welfare: completed primary profiles}\par\medskip",$"Coverage: {cases.Length} of {plan.Cases.Length} article-selected primary cases; {pairs.Length} of {plan.Welfare.Length} American/British comparisons. Pending cases are listed in the source data.\\par\\smallskip",@"These are five separate monetary measures, in damages units and weighted over potential disputes. They do not form an additive welfare index. The truth relationship is the baseline identity map. Alternative truth assumptions are not included.\par\smallskip",@"RN denotes risk neutrality; RA denotes symmetric CARA risk aversion (alpha in parentheses). Asymmetric cases state each party\textquotesingle s alpha. American and British are the main rules. Trial-only fee shifting appears as a separate ordinary-cost extension.\par\smallskip",@"Levels use the established truth-prior weighting of truth-conditional outcomes; direct replay truth mass is retained separately in the source catalog. Values are displayed to three decimals; calculations and comparisons use unrounded data. $\dagger$ marks a nonzero value that rounds to zero.\par\medskip",@"\small\setlength{\tabcolsep}{4pt}\begin{longtable}{@{}p{3.0in}llrrrrr@{}}",@"\toprule Specification & Risk & Fee & P shortfall & D nonliable & D liable excess & Gross error & Real costs\\\midrule\endfirsthead",@"\toprule Specification & Risk & Fee & P shortfall & D nonliable & D liable excess & Gross error & Real costs\\\midrule\endhead\bottomrule\endfoot"]);
        foreach(var c in cases)lines.Add(string.Join(" & ",new[]{Tex(Specification(c)),Tex(Risk(c)),c.FeeRule=="american"?"American":c.FeeRule=="complete"?"British":"Trial only"}.Concat(WelfareFigure.Measures.Select(m=>Number(Level(c.Id,m)))))+@"\\");
        lines.AddRange([@"\end{longtable}\normalsize\newpage",@"{\LARGE\bfseries Matched fee comparisons}\par\medskip",@"Every difference is British minus American under the same specification, costs and risk preferences. Each listed pair has passed the four-corner rule/behavior decomposition and complete endpoint checks.\par\medskip",@"\small\begin{longtable}{@{}lp{3.0in}lrrrrr@{}}",@"\toprule Code & Specification & Risk & P shortfall & D nonliable & D liable excess & Gross error & Real costs\\\midrule\endfirsthead",@"\toprule Code & Specification & Risk & P shortfall & D nonliable & D liable excess & Gross error & Real costs\\\midrule\endhead\bottomrule\endfoot"]);
        for(int i=0;i<pairs.Length;i++){var c=plan.Cases.Single(c=>c.Id==pairs[i].Source);lines.Add(string.Join(" & ",new[]{$"C{i+1:D2}",Tex(Specification(c)),Tex(Risk(c))}.Concat(Labels.Select(m=>Number(data[i]["Components"]![m]!["TotalDifference"]!.GetValue<double>()))))+@"\\");}
        lines.Add(@"\end{longtable}\normalsize");
        foreach(string label in Labels)
        {
            double[] values=data.Select(d=>d["Components"]![label]!["TotalDifference"]!.GetValue<double>()).ToArray();double bound=Math.Max(.002,values.Max(v=>Math.Abs(v))*1.3),scale=Math.Pow(10,Math.Floor(Math.Log10(bound/3))),tick=Math.Max(.001,new[]{1,2,5,10}.Select(f=>f*scale).First(v=>v>=bound/3));bound=Math.Ceiling(bound/tick)*tick;int n=(int)Math.Floor(bound/tick);
            lines.AddRange([@"\newpage{\LARGE\bfseries "+Tex(label)+@"}\par\smallskip",@"British minus American, using unrounded values. Codes identify the preceding matched-comparison table. Blue: negative; orange: positive. This is one monetary measure, not a combined policy ranking.\par\medskip",@"\begin{center}\begin{tikzpicture}\begin{axis}[width=9.7in,height=6.25in,"+$"xmin={-bound:G17},xmax={bound:G17},ymin=.5,ymax={pairs.Length+.5:G17},y dir=reverse,", "ytick={"+string.Join(',',Enumerable.Range(1,pairs.Length))+"},yticklabels={"+string.Join(',',Enumerable.Range(1,pairs.Length).Select(i=>$"C{i:D2}"))+"},xtick={"+string.Join(',',Enumerable.Range(-n,2*n+1).Select(i=>(i*tick).ToString("G17")))+"},",@"xticklabel style={/pgf/number format/fixed,/pgf/number format/precision=3,/pgf/number format/fixed zerofill},xlabel={Difference in damages units},ylabel={Matched comparison},grid=major,clip=false]",@"\addplot[gray,thin] coordinates {(0,.5) (0,"+(pairs.Length+.5).ToString("G")+")};"]);
            for(int i=0;i<values.Length;i++){double v=values[i];lines.Add($"\\addplot[only marks,mark=*,mark size=2.2pt,color={(v<0?"blue!65!black":v>0?"orange!85!black":"black")}] coordinates {{({v:G17},{i+1})}};");lines.Add($"\\node[font=\\small,anchor={(v>=0?"west":"east")}] at (axis cs:{v+(v>=0?1:-1)*bound*.016:G17},{i+1}) {{{Number(v)}}};");}
            lines.Add(@"\end{axis}\end{tikzpicture}\end{center}");
        }
        lines.Add(@"\end{document}");File.WriteAllText(Path.Combine(root,"Sources/welfare-overview.tex"),string.Join('\n',lines));
        lines=Begin(".5","amsmath");lines.AddRange([@"{\LARGE\bfseries Welfare decompositions: rule and behavior}\par\medskip",$"{pairs.Length} of {plan.Welfare.Length} American/British pairs are available. Each pair uses independently audited full profiles, including agreement and off-path actions. Alternative truth maps are not included.\\par\\smallskip",@"Write $W_{rs}$ for welfare evaluated under rule $r$ with the complete profile solved under rule $s$; $A$ denotes American and $C$ denotes British. The mixed corners are evaluations of fixed profiles, not new equilibria. The effects average the two replacement orders:\par",@"\[R=\tfrac12[(W_{CA}-W_{AA})+(W_{CC}-W_{AC})],\qquad B=\tfrac12[(W_{AC}-W_{AA})+(W_{CC}-W_{CA})].\]",@"The signed total is $\Delta=W_{CC}-W_{AA}=R+B$. No equilibrium-selection inference follows from this accounting decomposition. Five separate measures retain their existing definitions.\par\medskip",@"\small\begin{longtable}{@{}lp{5.4in}l@{}}\toprule Code & Matched specification and cost & Risk\\\midrule\endfirsthead",@"\toprule Code & Matched specification and cost & Risk\\\midrule\endhead\bottomrule\endfoot"]);
        for(int i=0;i<pairs.Length;i++){var c=plan.Cases.Single(c=>c.Id==pairs[i].Source);lines.Add($"C{i+1:D2} & {Tex(Specification(c))} & {Tex(Risk(c))}"+@"\\");}lines.Add(@"\end{longtable}\normalsize");
        foreach(string label in Labels)
        {
            lines.AddRange([@"\newpage{\LARGE\bfseries "+Tex(label)+@"}\par\medskip",@"Each row is a matched comparison from the preceding key. $R$ is the mechanical rule effect; $B$ the behavioral effect; $\Delta$ British minus American. Four significant figures are shown; all calculations retain unrounded corners. Tiny nonzero residuals are printed, not clipped.\par\medskip",@"\small\setlength{\tabcolsep}{6pt}\begin{longtable}{@{}lrrrrrrrr@{}}",@"\toprule Code & $W_{AA}$ & $W_{CA}$ & $W_{AC}$ & $W_{CC}$ & $R$ & $B$ & $\Delta$ & Residual\\\midrule\endfirsthead",@"\toprule Code & $W_{AA}$ & $W_{CA}$ & $W_{AC}$ & $W_{CC}$ & $R$ & $B$ & $\Delta$ & Residual\\\midrule\endhead\bottomrule\endfoot"]);
            for(int i=0;i<pairs.Length;i++){var c=data[i]["Components"]![label]!;lines.Add($"C{i+1:D2} & "+string.Join(" & ",new[]{"AmericanWithAmericanProfile","CompleteWithAmericanProfile","AmericanWithCompleteProfile","CompleteWithCompleteProfile","MechanicalRuleEffect","BehavioralEffect","TotalDifference","Residual"}.Select(k=>c[k]!.GetValue<double>().ToString("G4").ToLowerInvariant()))+@"\\[1pt]");}lines.Add(@"\end{longtable}\normalsize");
        }
        lines.Add(@"\end{document}");File.WriteAllText(Path.Combine(root,"Sources/welfare-decompositions.tex"),string.Join('\n',lines));
        File.WriteAllText(Path.Combine(root,"README.md"),$"# Generated pairwise comparisons\n\n{pairs.Length} of {plan.Welfare.Length} comparisons are available.\n\n- [Welfare levels and differences](welfare-overview.pdf)\n- [Four-corner decompositions](welfare-decompositions.pdf)\n- [Unrounded data and missing cases](Sources/welfare.generated-data.json)\n");
    }
}
