using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ACESim
{
    /// <summary>
    /// A struct to be stored in GameProgress that stores the actions generated by the standard dispute generator
    /// (thus saving the need to inherit from GameProgress). 
    /// </summary>
    [Serializable]
    public struct LitigGameStandardDisputeGeneratorActions
    {
        
        public byte PrePrimaryChanceAction, PrimaryAction, PostPrimaryChanceAction;
    }
}




