using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ACESimBase.GameSolvingSupport.ECTAAlgorithm
{
	public class node
	{
		public bool terminal; // 0: decision node / 1: terminal node
		public int iset = -1; // which information set
		public int father = -1; // node closer to root
		public int reachedby = -1; // move of edge from father
		public int outcome = -1; // which outcome
		/* will be generated by  genseqin()                                 */
		public int[] defseq = new int[] { 0, 0, 0 }; // seq defd by node for each player
	}
}
