using ACESimBase.Games.LitigGame.ManualReports;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static ACESimBase.Games.LitigGame.ManualReports.ArticlePressureAnalysis;
using static ACESimBase.Games.LitigGame.ManualReports.EquilibriumChangeDecomposition;

namespace LitigCharts;

/// <summary>Saved-equilibrium coordinates selected by strict action-loss or offsetting-effect checks.</summary>
public static class EquilibriumPublicationTables
{
    // Relative to Tables/Sources. Shared documentation is generated by the
    // supplemental planner; individual table sources contain only their data.
    public const string MethodologyFile = "../../Methodology and Explanation.md";
    public sealed record Group(ChangeRow[] Rows)
    {
        public ChangeRow First => Rows[0];
        public ChangeRow Last => Rows[^1];
        public string Sensitivity => SensitivityLabel(Rows);
    }

    public static async Task<int> RunAsync(string[] args)
    {
        try
        {
            var arguments = new Dictionary<string, string>();
            for (int i = 0; i < args.Length; i += 2)
            {
                if (i + 1 == args.Length || !new[] { "--request", "--output", "--previews" }.Contains(args[i]) ||
                    !arguments.TryAdd(args[i], Path.GetFullPath(args[i + 1])))
                    throw new ArgumentException("equilibrium-publication --request <calculation request> --output <directory> [--previews <QA directory>]");
            }
            if (new[] { "--request", "--output" }.Any(k => !arguments.ContainsKey(k)))
                throw new ArgumentException("Supply request and output; previews is optional.");
            string output = arguments["--output"], previews = arguments.GetValueOrDefault("--previews");
            if (previews != null && output.Equals(previews, StringComparison.OrdinalIgnoreCase))
                throw new ArgumentException("Keep QA previews outside the publication directory.");
            var calculated = EquilibriumChangeTables.LoadCalculated(arguments["--request"]);
            var publications = calculated.Results.Select(r => (Original: r, Rows: Select(r), Name: FileName(r))).ToArray();
            if (publications.Length == 0 || publications.Select(p => p.Name).Distinct().Count() != publications.Length)
                throw new InvalidDataException("Supply a nonempty set of uniquely identified directed contrasts.");
            if (calculated.Manifest.OutputJsonFiles.Any(p => Path.GetDirectoryName(p).Equals(output, StringComparison.OrdinalIgnoreCase)))
                throw new InvalidDataException("Do not write table files in a calculation directory.");
            Directory.CreateDirectory(output);
            Directory.CreateDirectory(Path.Combine(output, "Sources"));
            var sources = new List<string>();
            foreach (var p in publications)
            {
                string path = Path.Combine(output, "Sources", p.Name + ".tex");
                string provenance = "% Input request SHA-256: " + Hash(arguments["--request"]).Sha256;
                await File.WriteAllTextAsync(path, provenance + "\n" + Latex(p.Original, p.Rows));
                await File.WriteAllTextAsync(Path.ChangeExtension(path, ".json"), System.Text.Json.JsonSerializer.Serialize(new {
                    p.Original.Contrast, p.Original.SourceOptionSet, p.Original.TargetOptionSet,
                    SelectedRows = p.Rows, Inputs = new[] { Hash(arguments["--request"]) },
                    Selection = "Strict conditional action-loss or offsetting-effect criterion in the saved equilibria; residual and sensitivity retained",
                    Methodology = MethodologyFile }, JsonOptions));
                sources.Add(path);
                Console.WriteLine($"{p.Name}: {p.Rows.Length} information sets, {GroupRows(p.Rows).Length} displayed rows.");
            }
            await DiagramCompiler.CompileAllAsync(sources.ToArray(), new(), Environment.ProcessorCount, previewDirectory: previews);
            Console.WriteLine("Publication directory: " + output);
            return 0;
        }
        catch (Exception e) { Console.Error.WriteLine(e); return 1; }
    }

    public static ChangeRow[] Select(ContrastResult original)
    {
        var keys = EquilibriumChangeFocus.Build(original, original.Tolerances.NearTie)
            .Where(i => i.Focus).Select(i => i.Key).ToHashSet();
        var selected = original.Changes.Where(r => keys.Contains(r.Key))
            .Concat(OffsettingEffects(original)).ToArray();
        ValidateRows(selected);
        return selected;
    }

    public static bool Unchanged(ChangeRow row) =>
        row.OriginalPolicy.Zip(row.TargetPolicy, (a, b) => Math.Abs(a - b)).Max() <= PolicyTolerance;

    /// <summary>
    /// An unchanged endpoint policy is strictly suboptimal after the intervention
    /// alone, but restored by the all-target-opponent best response. Uses cached
    /// unrestricted responses, never a fresh equilibrium or an imposed causal path.
    /// </summary>
    public static ChangeRow[] OffsettingEffects(ContrastResult result)
    {
        bool Qualifies(ChangeRow row)
        {
            if (!Unchanged(row) || row.CounterfactualUndefined ||
                Math.Abs(row.Allocation.Direct) <= PolicyTolerance ||
                Math.Abs(row.Allocation.SelectionResidual) > PolicyTolerance) return false;
            var direct = result.Scenarios.Single(s => s.Panel == "coalition" && s.Component == "0" && s.Result.Player == row.Player)
                .Result.InformationSets.Single(s => s.Key == row.Key);
            var all = result.Scenarios.Single(s => s.Panel == "coalition" && s.Component == "7" && s.Result.Player == row.Player)
                .Result.InformationSets.Single(s => s.Key == row.Key);
            if (direct.CounterfactuallyUnreachable || direct.Actions.Any(a =>
                !a.CounterfactualConditionalUtility.HasValue || !double.IsFinite(a.CounterfactualConditionalUtility.Value)) ||
                all.Actions.Zip(row.TargetPolicy, (a, p) => Math.Abs(a.Probability - p)).Max() > PolicyTolerance) return false;
            double best = direct.Actions.Max(a => a.CounterfactualConditionalUtility.Value);
            double inferiorMass = direct.Actions.Select((a, i) =>
                best - a.CounterfactualConditionalUtility.Value > result.Tolerances.NearTie ? row.OriginalPolicy[i] : 0).Sum();
            return inferiorMass > PolicyTolerance;
        }
        return BuildRows(result.SourceEquilibrium, result.TargetEquilibrium, result.Scenarios,
            result.OfferValues, includeUnchanged: true).Rows.Where(Qualifies).ToArray();
    }

    public static void ValidateRows(ChangeRow[] rows)
    {
        if (rows.Select(r => (r.Key,r.Action)).Distinct().Count() != rows.Length ||
            rows.Any(r => r.Metric is not ("decision probability" or "offer amount" or "offer action probability")))
            throw new InvalidDataException("Duplicate or unsupported strategy coordinates.");
        foreach (var r in rows.Where(r=>!r.CounterfactualUndefined))
            InformationSetPressureAnalysis.Near(r.Allocation.Change, r.Allocation.Explained + r.Allocation.SelectionResidual,
                PolicyTolerance, "Publication accounting including residual");
    }

    public static Group[] GroupRows(ChangeRow[] rows)
    {
        var groups = new List<Group>();
        foreach (var row in rows)
        {
            if (groups.Count > 0 && CanCombine(groups[^1].Last, row))
                groups[^1] = new(groups[^1].Rows.Append(row).ToArray());
            else groups.Add(new(new[] { row }));
        }
        return groups.ToArray();
    }

    private static bool CanCombine(ChangeRow a, ChangeRow b)
    {
        bool Same(double[] x, double[] y) => x.Length == y.Length && x.Zip(y, (u, v) => Math.Abs(u - v)).All(d => d <= PolicyTolerance);
        double[] Values(ChangeRow r) => new[] { r.Allocation.Original, r.Allocation.Target, r.Allocation.Direct,
            r.Allocation.Entry, r.Allocation.Offers, r.Allocation.Exit, r.Allocation.SelectionResidual };
        return a.Player == b.Player && a.Decision == b.Decision && a.Signal + 1 == b.Signal &&
            a.ExitCommitment == b.ExitCommitment && a.Metric == b.Metric && a.Action == b.Action &&
            a.CounterfactualUndefined == b.CounterfactualUndefined && a.UnreachedCoalitions.SequenceEqual(b.UnreachedCoalitions) &&
            Same(a.OriginalPolicy, b.OriginalPolicy) && Same(a.TargetPolicy, b.TargetPolicy) && Same(Values(a), Values(b));
        // Unlike the audit packet, combine equal numerical rows with different flags.
        // The displayed group explicitly distinguishes sensitivity at all/some/no signals.
    }

    public static string SensitivityLabel(ChangeRow[] rows)
    {
        int count = rows.Count(r => r.TieSensitive || r.CompletionSensitive);
        return count == 0 ? "No" : count == rows.Length ? "Yes" : "At some signals";
    }

    public static string FileName(ContrastResult r)
    {
        EquilibriumChangeTables.Heading(r.SourceOptionSet, r.TargetOptionSet);
        return r.Contrast.Id;
    }

    public static string Latex(ContrastResult result, ChangeRow[] rows)
    {
        ValidateRows(rows);
        var h = EquilibriumChangeTables.Heading(result.SourceOptionSet, result.TargetOptionSet);
        var b = new StringBuilder("""
            \documentclass[10pt,border=8pt,varwidth=7.5in]{standalone}
            \usepackage[T1]{fontenc}
            \usepackage{lmodern,booktabs,array,tabularx,microtype}
            \setlength{\parindent}{0pt}
            \setlength{\tabcolsep}{3.5pt}
            \renewcommand{\arraystretch}{1.22}
            \begin{document}
            \begin{minipage}{7.5in}
            """);
        b.AppendLine(@"{\fontsize{9.5}{11.5}\selectfont\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{1.35in}>{\centering\arraybackslash}p{.45in}>{\centering\arraybackslash}p{1.05in}*{5}{>{\centering\arraybackslash}X}>{\centering\arraybackslash}p{.65in}@{}}");
        b.AppendLine(@"\toprule Decision & Signal & Original $\to$ Target & Direct & \shortstack{Opponent\\entry} & \shortstack{Opponent\\offers} & \shortstack{Opponent\\exit} & Remaining & Sensitive \\\midrule");
        bool hasOffsets = rows.Any(Unchanged);
        foreach (var section in rows.GroupBy(Unchanged).OrderBy(g => g.Key))
        {
            if (hasOffsets)
                b.AppendLine((section.Key ? @"\midrule " : "") + @"\multicolumn{9}{l}{\textit{" +
                    (section.Key ? "Unchanged actions with offsetting effects" : "Changed actions") + @"}}\\[2pt]");
            foreach (var group in GroupRows(section.ToArray()))
            {
                var row = group.First; var a = row.Allocation;
                bool amount = row.Metric == "offer amount";
                string Num(double v, bool signed)
                {
                    if (Math.Abs(v) < (amount ? .0005 : .05)) v = 0;
                    return (signed && v > 0 ? "+" : "") + v.ToString(amount ? "0.00#" : "0.#", CultureInfo.InvariantCulture);
                }
                string endpoint = "$" + Num(a.Original, false) + (amount ? "" : @"\%") + @"\to " + Num(a.Target, false) + (amount ? "" : @"\%") + "$";
                string label = row.Decision switch
                {
                    "P Files" => "P files",
                    "D Answers" => "D answers",
                    "P Abandons" => "P commits to abandon",
                    "D Defaults" => "D commits to default",
                    _ => (row.Player == 0 ? "P demand" : "D offer") + (row.ExitCommitment == 2 ? ", continue" : ", exit")
                };
                if (row.Action.HasValue) label += " " + EquilibriumChangeTables.Escape(row.ActionLabels[row.Action.Value-1]);
                string signal = row.SignalValue.ToString("0.00", CultureInfo.InvariantCulture) +
                    (group.Rows.Length > 1 ? "--" + group.Last.SignalValue.ToString("0.00", CultureInfo.InvariantCulture) : "");
                if (group.Rows.Any(r => r.UnreachedCoalitions.Length > 0)) label += "$^{*}$";
                b.Append(label + " & " + signal + " & " + endpoint);
                foreach (double effect in new[] { a.Direct, a.Entry, a.Offers, a.Exit, a.SelectionResidual })
                    b.Append(row.CounterfactualUndefined ? " & ---" : " & $" + Num(effect, true) + "$");
                b.AppendLine(" & " + group.Sensitivity + @"\\");
            }
        }
        return b.AppendLine(@"\bottomrule\end{tabularx}}\end{minipage}\end{document}").ToString();
    }
}
